
# FILES
defaults:  # (these specify which config FILES to use)
  ############## TRAIN ###################################
  - train/config: splade_synonyms
  - train/data: synonyms
  - train/model: splade
  ############## INDEX ###################################
  - index: toy
  ############## RETRIEVE ################################
  - retrieve_evaluate: toy
  ############### FLOPS ##################################
  - flops: toy

# Direct PARAMETER setting
config:  # to be provided for each run
  checkpoint_dir: "/home/nicolas/stage/splade/outputs/checkpoints"
  index_dir: "/home/nicolas/stage/splade/outputs/index"
  out_dir: "/home/nicolas/stage/splade/outputs"
  fp16: false
