defaults:  # (these specify which config FILES to use)
  - rerank_collection: msmarco_trec19
  - rerank_runs: new_baseline_trec19

config:  # to be provided for each run
  out_dir: experiments/rerankers/rankT5_3b/out/
  pretrained_no_yamlconfig: True
  tokenizer_type: t5-3b
  lr: 2e-5
  seed: 123
  gradient_accumulation_steps: 1
  weight_decay: 0.01
  max_length: 512
  eval_batch_size: 200
  reranker_type: rankT5
  checkpoint: /gfs-ssd/project/neuralsearch/models/trecdl22-crossencoder-rankT53b-repro/pytorch_model.bin
  top_k: 100
  add_prefix: True

init_dict:
  model_type_or_dir: t5-3b
  fp16: false
  bf16: true

ir_datasets:
  dataset_path: /gfs-ssd/project/neuralsearch/bkup/classanc/ir_datasets/