defaults:  # (these specify which config FILES to use)
  - rerank_collection: msmarco_trec19
  - rerank_runs: new_baseline_trec19

config:  # to be provided for each run
  out_dir: experiments/rerankers/roberta/out/
  pretrained_no_yamlconfig: True
  tokenizer_type: naver/trecdl22-crossencoder-roberta
  index_retrieve_batch_size: 200
  batch_size: 200
  max_length: 512
  eval_batch_size: 200
  reranker_type: roberta
  top_k: 1000
  return_token_type_ids: True
  add_prefix: False

init_dict:
  model_type_or_dir: naver/trecdl22-crossencoder-roberta
  fp16: true
  bf16: false

ir_datasets:
  dataset_path: /gfs-ssd/project/neuralsearch/bkup/classanc/ir_datasets/